services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/home/ada/data

  cldcmder:
    image: coderaiser/cloudcmd
    platform: linux/amd64
    container_name: cldcmder
    ports:
      - "8000:8000"
    volumes:
      - a3compose_a3_server:/mnt/server_files
    command: "cloudcmd --prefix /files --one-file-panel --root=/mnt/server_files --auth --username admin --password ${CMD_PASS}"
    restart: unless-stopped

volumes:
  # postgres
  pgdata:
  # arma 3
  a3compose_a3_server:
    external: true
