services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/home/ada/data

  cldcmder:
    image: coderaiser/cloudcmd
    platform: linux/amd64
    container_name: cldcmder
    ports:
      - "8000:8000"
    volumes:
      - a3_server:/mnt/server_files
    command: "cloudcmd --one-file-panel --root=/mnt/server_files --auth"
    environment:
      CLOUDCMD_USERNAME: admin
      CLOUDCMD_PASSWORD: ${CMD_PASS}
    restart: unless-stopped

volumes:
  # postgres
  pgdata:
  # arma 3
  a3_server: